/**
 * Desafios da Roleta (Verdade ou Consequência / o que preferes): o Vozen le UM em voz
 * alta. Conteudo leve e amigavel. Por locale de INTERFACE da guild (ctx.locale); cai
 * em ingles se a lingua nao tiver banco.
 */
export const ROULETTE_PROMPTS: Record<string, string[]> = {
  en: [
    'Truth: what is the most embarrassing song on your playlist?',
    'Dare: send the last emoji you used, ten times in a row.',
    'Would you rather always be ten minutes late or twenty minutes early?',
    'Truth: what is a small thing that makes you irrationally happy?',
    'Dare: type your next message using only your nose.',
    'Would you rather have unlimited pizza or unlimited tacos for life?',
    'Truth: what is the weirdest food combination you secretly love?',
    'Dare: describe your day using only three emojis.',
    'Would you rather be able to fly or be invisible?',
    'Truth: what is the last lie you told (a small one)?',
    'Dare: give the person above you a genuine compliment.',
    'Would you rather never use social media again or never watch another movie?',
    'Truth: which app do you spend way too much time on?',
    'Truth: what was your childhood nickname?',
    'Truth: which song do you secretly know all the words to?',
    'Truth: what is the strangest dream you remember?',
    'Truth: which emoji describes you best, and why?',
    'Truth: what is your most useless talent?',
    'Truth: what food could you happily eat every single day?',
    'Truth: what would you do with one day of invisibility?',
    'Dare: write your next message completely backwards.',
    'Dare: type the whole alphabet as fast as you can.',
    'Dare: describe the last photo in your gallery (words only).',
    'Dare: answer only with questions for the next five minutes.',
    'Dare: invent a new word and use it in a sentence.',
    'Dare: write a two line poem about the person above you.',
    'Dare: use only capital letters in your next three messages.',
    'Dare: tell a joke — if nobody laughs, tell another one.',
    'Would you rather live without music or without movies?',
    'Would you rather always whisper or always shout?',
    'Would you rather have a pet dragon or be a dragon?',
    'Would you rather travel to the past or to the future?',
    'Would you rather never eat sweets again or never eat snacks again?',
    'Would you rather be a cat or a dog for a week?',
    'Would you rather read minds or teleport anywhere?',
    'Would you rather live at the beach or in the mountains?',
  ],
  pt: [
    'Verdade: qual é a música mais embaraçosa da tua playlist?',
    'Consequência: manda o último emoji que usaste, dez vezes seguidas.',
    'O que preferes: chegar sempre dez minutos atrasado ou vinte minutos adiantado?',
    'Verdade: que pequena coisa te deixa irracionalmente feliz?',
    'Consequência: escreve a próxima mensagem só com o nariz.',
    'O que preferes: pizza ilimitada ou tacos ilimitados para a vida toda?',
    'Verdade: qual é a combinação de comida mais estranha que adoras em segredo?',
    'Consequência: descreve o teu dia usando só três emojis.',
    'O que preferes: conseguir voar ou ser invisível?',
    'Verdade: qual foi a última mentira (pequenina) que contaste?',
    'Consequência: faz um elogio sincero à pessoa acima de ti.',
    'O que preferes: nunca mais usar redes sociais ou nunca mais ver um filme?',
    'Verdade: em que app passas demasiado tempo?',
    'Verdade: qual era a tua alcunha em criança?',
    'Verdade: que música sabes de cor em segredo?',
    'Verdade: qual é o sonho mais estranho de que te lembras?',
    'Verdade: que emoji te descreve melhor, e porquê?',
    'Verdade: qual é o teu talento mais inútil?',
    'Verdade: que comida conseguias comer todos os dias?',
    'Verdade: o que farias com um dia de invisibilidade?',
    'Consequência: escreve a tua próxima mensagem toda ao contrário.',
    'Consequência: escreve o alfabeto inteiro o mais depressa que conseguires.',
    'Consequência: descreve a última foto da tua galeria (só por palavras).',
    'Consequência: responde só com perguntas durante cinco minutos.',
    'Consequência: inventa uma palavra nova e usa-a numa frase.',
    'Consequência: escreve um poema de duas linhas sobre a pessoa acima de ti.',
    'Consequência: usa só maiúsculas nas próximas três mensagens.',
    'Consequência: conta uma piada — se ninguém rir, conta outra.',
    'O que preferes: viver sem música ou sem filmes?',
    'O que preferes: sussurrar sempre ou gritar sempre?',
    'O que preferes: ter um dragão de estimação ou ser um dragão?',
    'O que preferes: viajar ao passado ou ao futuro?',
    'O que preferes: nunca mais comer doces ou nunca mais comer salgados?',
    'O que preferes: ser gato ou cão durante uma semana?',
    'O que preferes: ler mentes ou teletransportar-te para qualquer lugar?',
    'O que preferes: viver na praia ou na montanha?',
  ],
  es: [
    'Verdad: ¿cuál es la canción más vergonzosa de tu lista de reproducción?',
    'Reto: envía el último emoji que usaste, diez veces seguidas.',
    '¿Qué prefieres: llegar siempre diez minutos tarde o veinte minutos antes?',
    'Verdad: ¿qué pequeña cosa te hace irracionalmente feliz?',
    'Reto: escribe tu próximo mensaje usando solo la nariz.',
    '¿Qué prefieres: pizza ilimitada o tacos ilimitados de por vida?',
    'Verdad: ¿cuál es la combinación de comida más rara que te encanta en secreto?',
    'Reto: describe tu día usando solo tres emojis.',
    '¿Qué prefieres: poder volar o ser invisible?',
    'Verdad: ¿cuál fue la última mentira (pequeña) que dijiste?',
    'Reto: hazle un cumplido sincero a la persona de arriba.',
    '¿Qué prefieres: no volver a usar redes sociales o no ver otra película?',
    'Verdad: ¿en qué app pasas demasiado tiempo?',
    'Verdad: ¿cuál era tu apodo de pequeño?',
    'Verdad: ¿qué canción te sabes de memoria en secreto?',
    'Verdad: ¿cuál es el sueño más raro que recuerdas?',
    'Verdad: ¿qué emoji te describe mejor, y por qué?',
    'Verdad: ¿cuál es tu talento más inútil?',
    'Verdad: ¿qué comida podrías comer todos los días?',
    'Verdad: ¿qué harías con un día de invisibilidad?',
    'Reto: escribe tu próximo mensaje completamente al revés.',
    'Reto: escribe el abecedario entero lo más rápido que puedas.',
    'Reto: describe la última foto de tu galería (solo con palabras).',
    'Reto: responde solo con preguntas durante cinco minutos.',
    'Reto: inventa una palabra nueva y úsala en una frase.',
    'Reto: escribe un poema de dos líneas sobre la persona de arriba.',
    'Reto: usa solo mayúsculas en tus próximos tres mensajes.',
    'Reto: cuenta un chiste — si nadie se ríe, cuenta otro.',
    '¿Qué prefieres: vivir sin música o sin películas?',
    '¿Qué prefieres: susurrar siempre o gritar siempre?',
    '¿Qué prefieres: tener un dragón de mascota o ser un dragón?',
    '¿Qué prefieres: viajar al pasado o al futuro?',
    '¿Qué prefieres: no comer dulces nunca más o no comer salado nunca más?',
    '¿Qué prefieres: ser gato o perro durante una semana?',
    '¿Qué prefieres: leer mentes o teletransportarte a cualquier lugar?',
    '¿Qué prefieres: vivir en la playa o en la montaña?',
  ],
  fr: [
    'Vérité : quelle est la chanson la plus gênante de ta playlist ?',
    'Action : envoie le dernier emoji que tu as utilisé, dix fois de suite.',
    'Tu préfères arriver toujours dix minutes en retard ou vingt minutes en avance ?',
    'Vérité : quelle petite chose te rend irrationnellement heureux ?',
    'Action : écris ton prochain message uniquement avec le nez.',
    'Tu préfères pizza illimitée ou tacos illimités à vie ?',
    'Vérité : quelle est la combinaison de nourriture la plus bizarre que tu adores en secret ?',
    'Action : décris ta journée avec seulement trois emojis.',
    'Tu préfères pouvoir voler ou être invisible ?',
    'Vérité : quel est le dernier petit mensonge que tu as dit ?',
    'Action : fais un compliment sincère à la personne au-dessus de toi.',
    'Tu préfères ne plus jamais utiliser les réseaux sociaux ou ne plus jamais voir un film ?',
    'Vérité : sur quelle appli passes-tu beaucoup trop de temps ?',
    'Vérité : quel était ton surnom quand tu étais petit ?',
    'Vérité : quelle chanson connais-tu par cœur en secret ?',
    'Vérité : quel est le rêve le plus étrange dont tu te souviens ?',
    'Vérité : quel emoji te décrit le mieux, et pourquoi ?',
    'Vérité : quel est ton talent le plus inutile ?',
    'Vérité : quel plat pourrais-tu manger tous les jours ?',
    'Vérité : que ferais-tu avec une journée d’invisibilité ?',
    'Action : écris ton prochain message complètement à l’envers.',
    'Action : tape tout l’alphabet le plus vite possible.',
    'Action : décris la dernière photo de ta galerie (avec des mots seulement).',
    'Action : réponds uniquement par des questions pendant cinq minutes.',
    'Action : invente un nouveau mot et utilise-le dans une phrase.',
    'Action : écris un poème de deux lignes sur la personne au-dessus de toi.',
    'Action : écris tes trois prochains messages en majuscules.',
    'Action : raconte une blague — si personne ne rit, racontes-en une autre.',
    'Tu préfères vivre sans musique ou sans films ?',
    'Tu préfères toujours chuchoter ou toujours crier ?',
    'Tu préfères avoir un dragon de compagnie ou être un dragon ?',
    'Tu préfères voyager dans le passé ou dans le futur ?',
    'Tu préfères ne plus jamais manger de sucré ou ne plus jamais manger de salé ?',
    'Tu préfères être un chat ou un chien pendant une semaine ?',
    'Tu préfères lire dans les pensées ou te téléporter n’importe où ?',
    'Tu préfères vivre à la plage ou à la montagne ?',
  ],
  de: [
    'Wahrheit: Was ist das peinlichste Lied in deiner Playlist?',
    'Pflicht: Schick das letzte Emoji, das du benutzt hast, zehnmal hintereinander.',
    'Was ist dir lieber: immer zehn Minuten zu spät oder zwanzig Minuten zu früh?',
    'Wahrheit: Welche kleine Sache macht dich unvernünftig glücklich?',
    'Pflicht: Schreib deine nächste Nachricht nur mit der Nase.',
    'Was ist dir lieber: unbegrenzt Pizza oder unbegrenzt Tacos fürs Leben?',
    'Wahrheit: Was ist die seltsamste Essenskombination, die du heimlich liebst?',
    'Pflicht: Beschreib deinen Tag mit nur drei Emojis.',
    'Was ist dir lieber: fliegen können oder unsichtbar sein?',
    'Wahrheit: Was war die letzte (kleine) Lüge, die du erzählt hast?',
    'Pflicht: Mach der Person über dir ein ehrliches Kompliment.',
    'Was ist dir lieber: nie wieder soziale Medien oder nie wieder einen Film sehen?',
    'Wahrheit: In welcher App verbringst du viel zu viel Zeit?',
    'Wahrheit: Was war dein Spitzname als Kind?',
    'Wahrheit: Welches Lied kennst du heimlich auswendig?',
    'Wahrheit: Was ist der seltsamste Traum, an den du dich erinnerst?',
    'Wahrheit: Welches Emoji beschreibt dich am besten, und warum?',
    'Wahrheit: Was ist dein nutzlosestes Talent?',
    'Wahrheit: Welches Essen könntest du jeden Tag essen?',
    'Wahrheit: Was würdest du mit einem Tag Unsichtbarkeit machen?',
    'Pflicht: Schreib deine nächste Nachricht komplett rückwärts.',
    'Pflicht: Tipp das ganze Alphabet so schnell du kannst.',
    'Pflicht: Beschreib das letzte Foto in deiner Galerie (nur mit Worten).',
    'Pflicht: Antworte fünf Minuten lang nur mit Fragen.',
    'Pflicht: Erfinde ein neues Wort und benutze es in einem Satz.',
    'Pflicht: Schreib ein Zwei-Zeilen-Gedicht über die Person über dir.',
    'Pflicht: Schreib deine nächsten drei Nachrichten nur in Grossbuchstaben.',
    'Pflicht: Erzähl einen Witz — wenn niemand lacht, erzähl noch einen.',
    'Was ist dir lieber: ohne Musik oder ohne Filme leben?',
    'Was ist dir lieber: immer flüstern oder immer schreien?',
    'Was ist dir lieber: einen Drachen haben oder ein Drache sein?',
    'Was ist dir lieber: in die Vergangenheit oder in die Zukunft reisen?',
    'Was ist dir lieber: nie wieder Süsses oder nie wieder Salziges essen?',
    'Was ist dir lieber: eine Woche lang Katze oder Hund sein?',
    'Was ist dir lieber: Gedanken lesen oder dich überallhin teleportieren?',
    'Was ist dir lieber: am Strand oder in den Bergen leben?',
  ],
  it: [
    'Verità: qual è la canzone più imbarazzante della tua playlist?',
    'Obbligo: manda l’ultima emoji che hai usato, dieci volte di fila.',
    'Preferisci arrivare sempre dieci minuti in ritardo o venti minuti in anticipo?',
    'Verità: quale piccola cosa ti rende irrazionalmente felice?',
    'Obbligo: scrivi il prossimo messaggio usando solo il naso.',
    'Preferisci pizza illimitata o tacos illimitati a vita?',
    'Verità: qual è la combinazione di cibo più strana che adori in segreto?',
    'Obbligo: descrivi la tua giornata usando solo tre emoji.',
    'Preferisci saper volare o essere invisibile?',
    'Verità: qual è stata l’ultima piccola bugia che hai detto?',
    'Obbligo: fai un complimento sincero alla persona sopra di te.',
    'Preferisci non usare mai più i social o non vedere mai più un film?',
    'Verità: su quale app passi troppo tempo?',
    'Verità: qual era il tuo soprannome da piccolo?',
    'Verità: quale canzone conosci a memoria in segreto?',
    'Verità: qual è il sogno più strano che ricordi?',
    'Verità: quale emoji ti descrive meglio, e perché?',
    'Verità: qual è il tuo talento più inutile?',
    'Verità: quale cibo potresti mangiare tutti i giorni?',
    'Verità: cosa faresti con un giorno di invisibilità?',
    'Obbligo: scrivi il tuo prossimo messaggio completamente al contrario.',
    'Obbligo: scrivi tutto l’alfabeto il più velocemente possibile.',
    'Obbligo: descrivi l’ultima foto della tua galleria (solo a parole).',
    'Obbligo: rispondi solo con domande per i prossimi cinque minuti.',
    'Obbligo: inventa una parola nuova e usala in una frase.',
    'Obbligo: scrivi una poesia di due righe sulla persona sopra di te.',
    'Obbligo: scrivi i prossimi tre messaggi solo in maiuscolo.',
    'Obbligo: racconta una barzelletta — se nessuno ride, raccontane un’altra.',
    'Preferisci vivere senza musica o senza film?',
    'Preferisci sussurrare sempre o urlare sempre?',
    'Preferisci avere un drago o essere un drago?',
    'Preferisci viaggiare nel passato o nel futuro?',
    'Preferisci non mangiare mai più dolci o mai più salati?',
    'Preferisci essere un gatto o un cane per una settimana?',
    'Preferisci leggere nel pensiero o teletrasportarti ovunque?',
    'Preferisci vivere al mare o in montagna?',
  ],
};

/** Banco de desafios para o locale (base) da guild; fallback a ingles. PURA. */
export function pickPrompts(locale: string): string[] {
  const base = locale.split('-')[0].toLowerCase();
  return ROULETTE_PROMPTS[base] ?? ROULETTE_PROMPTS.en;
}
