import { baseCodeOf } from '../util';

/**
 * Frases CURTAS (3-6 palavras) por lingua-base, para o jogo da Velocidade Estupida: o
 * Vozen le-as MUITO depressa e o 1o a escrever o que ouviu ganha. Curtas de proposito —
 * a graca e decifrar, nao transcrever um paragrafo. Ditas na voz default da guild.
 */
export const SHORT_PHRASES: Record<string, string[]> = {
  en: [
    'the cat sat on the mat',
    'i love pizza with cheese',
    'the sun is very bright today',
    'my dog runs really fast',
    'we are going to the beach',
    'she sings a happy song',
    'the coffee is too hot',
    'birds fly over the river',
    'the moon shines at night',
    'my shoes are too small',
    'we dance in the rain',
    'the train leaves at noon',
    'her cake tastes like honey',
    'the frog jumps very high',
    'i lost my blue pencil',
    'the soup needs more salt',
    'his bike has a flat tire',
    'the stars are out tonight',
    'my phone is almost dead',
    'the bread smells so good',
    'we play chess after dinner',
    'the wind blows from the north',
    'my plant grows very slowly',
    'the clock stopped at midnight',
  ],
  pt: [
    'o gato dormiu no sofa',
    'eu adoro pizza com queijo',
    'o sol esta muito quente hoje',
    'o meu cao corre depressa',
    'vamos todos ate a praia',
    'ela canta uma cancao alegre',
    'o cafe esta demasiado quente',
    'os passaros voam sobre o rio',
    'a lua brilha de noite',
    'os meus sapatos sao pequenos',
    'gostamos de dancar na chuva',
    'o comboio parte ao meio dia',
    'o bolo sabe a mel',
    'o sapo salta muito alto',
    'perdi o meu lapis azul',
    'a sopa precisa de sal',
    'a minha bicicleta esta furada',
    'as estrelas brilham esta noite',
    'o meu telemovel esta sem bateria',
    'o pao cheira muito bem',
    'jogamos xadrez depois do jantar',
    'o vento sopra do norte',
    'a planta cresce devagar',
    'o relogio parou a meia noite',
  ],
  es: [
    'el gato duerme en el sofa',
    'me encanta la pizza con queso',
    'el sol esta muy caliente hoy',
    'mi perro corre muy rapido',
    'vamos todos a la playa',
    'ella canta una cancion alegre',
    'el cafe esta demasiado caliente',
    'los pajaros vuelan sobre el rio',
    'la luna brilla de noche',
    'mis zapatos son muy pequenos',
    'nos gusta bailar bajo la lluvia',
    'el tren sale al mediodia',
    'el pastel sabe a miel',
    'la rana salta muy alto',
    'perdi mi lapiz azul',
    'la sopa necesita mas sal',
    'mi bicicleta tiene una rueda rota',
    'las estrellas brillan esta noche',
    'mi movil esta sin bateria',
    'el pan huele muy bien',
    'jugamos ajedrez despues de cenar',
    'el viento sopla del norte',
    'la planta crece despacio',
    'el reloj se paro a medianoche',
  ],
  fr: [
    'le chat dort sur le canape',
    'jadore la pizza au fromage',
    'le soleil est tres chaud aujourdhui',
    'mon chien court tres vite',
    'nous allons tous a la plage',
    'elle chante une chanson joyeuse',
    'le cafe est trop chaud',
    'les oiseaux volent sur la riviere',
    'la lune brille la nuit',
    'mes chaussures sont trop petites',
    'nous dansons sous la pluie',
    'le train part a midi',
    'le gateau sent le miel',
    'la grenouille saute tres haut',
    'jai perdu mon crayon bleu',
    'la soupe manque de sel',
    'mon velo a une roue crevee',
    'les etoiles brillent ce soir',
    'mon telephone est presque vide',
    'le pain sent tres bon',
    'nous jouons aux echecs le soir',
    'le vent souffle du nord',
    'la plante pousse lentement',
    'lhorloge sest arretee a minuit',
  ],
  de: [
    'die katze schlaeft auf dem sofa',
    'ich liebe pizza mit kaese',
    'die sonne ist heute sehr heiss',
    'mein hund rennt sehr schnell',
    'wir gehen alle an den strand',
    'sie singt ein frohes lied',
    'der kaffee ist zu heiss',
    'die voegel fliegen ueber den fluss',
    'der mond scheint in der nacht',
    'meine schuhe sind zu klein',
    'wir tanzen im regen',
    'der zug faehrt um zwoelf',
    'der kuchen schmeckt nach honig',
    'der frosch springt sehr hoch',
    'ich habe meinen stift verloren',
    'die suppe braucht mehr salz',
    'mein fahrrad hat einen platten',
    'die sterne leuchten heute nacht',
    'mein handy ist fast leer',
    'das brot riecht so gut',
    'wir spielen schach nach dem essen',
    'der wind weht aus dem norden',
    'die pflanze waechst sehr langsam',
    'die uhr blieb um mitternacht stehen',
  ],
  it: [
    'il gatto dorme sul divano',
    'adoro la pizza al formaggio',
    'oggi il sole e molto caldo',
    'il mio cane corre veloce',
    'andiamo tutti alla spiaggia',
    'lei canta una canzone allegra',
    'il caffe e troppo caldo',
    'gli uccelli volano sul fiume',
    'la luna brilla di notte',
    'le mie scarpe sono piccole',
    'balliamo sotto la pioggia',
    'il treno parte a mezzogiorno',
    'la torta sa di miele',
    'la rana salta molto in alto',
    'ho perso la mia matita blu',
    'la zuppa ha bisogno di sale',
    'la mia bici ha una gomma a terra',
    'le stelle brillano stasera',
    'il mio telefono e quasi scarico',
    'il pane profuma tanto',
    'giochiamo a scacchi dopo cena',
    'il vento soffia da nord',
    'la pianta cresce lentamente',
    'lorologio si e fermato a mezzanotte',
  ],
};

export interface PhraseSource {
  base: string;
  model: string;
  phrases: string[];
}

/** Escolhe frases curtas + voz: lingua da voz default da guild se tiver banco; senao EN. */
export function pickPhraseSource(defaultVoice: string, availableModels: string[]): PhraseSource {
  const base = baseCodeOf(defaultVoice);
  if (SHORT_PHRASES[base]?.length) {
    return { base, model: defaultVoice, phrases: SHORT_PHRASES[base] };
  }
  const enModel = availableModels.find((m) => baseCodeOf(m) === 'en') ?? defaultVoice;
  return { base: 'en', model: enModel, phrases: SHORT_PHRASES.en };
}
