/**
 * tools/bench.ts — Vozen performance ruler (spec Phase 0 / T0.1).
 *
 * Run with:  npx tsx tools/bench.ts
 *
 * Measures, with the REAL Piper (uses PIPER_PATH/MODELS_DIR from .env):
 *  - COLD synthesis latency (cache miss) by text size (short/medium/long);
 *  - WARM latency (cache hit);
 *  - approximate spawn overhead (minimal-text synthesis);
 *  - cache hit-rate on a synthetic replay;
 *  - RAM (rss) and the resolved concurrency cap.
 * Writes/updates BENCHMARKS.md with the baseline. PURE relative to the bot (doesn't
 * connect to Discord; uses an isolated temporary cache). NOT part of the production build.
 *
 * NOTE (motivates T2.2): today there is NO streaming — audio only plays once the whole
 * WAV is ready, so "time to first word" == total synthesis time measured here.
 */
import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, join } from 'node:path';
import { loadConfig } from '../src/config/index';
import { AudioCache } from '../src/tts/cache';
import { PiperEngine, resolvePiperConcurrency, shutdownPiperPool } from '../src/tts/piper';
import type { SynthRequest } from '../src/tts/engine';

function discoverModels(modelsDir: string): string[] {
  if (!existsSync(modelsDir)) return [];
  return readdirSync(modelsDir)
    .filter((f) => f.endsWith('.onnx'))
    .map((f) => basename(f, '.onnx'))
    .sort();
}

function percentile(sortedMs: number[], p: number): number {
  if (sortedMs.length === 0) return NaN;
  const idx = Math.min(sortedMs.length - 1, Math.floor((p / 100) * sortedMs.length));
  return sortedMs[idx];
}

function stats(ms: number[]): { p50: number; p95: number; min: number; max: number } {
  const s = [...ms].sort((a, b) => a - b);
  return { p50: percentile(s, 50), p95: percentile(s, 95), min: s[0], max: s[s.length - 1] };
}

const WORD = 'a nossa cidade tem um tempo muito agradavel durante toda a semana inteira ';
function words(n: number): string {
  const base = WORD.trim().split(' ');
  const out: string[] = [];
  while (out.length < n) out.push(base[out.length % base.length]);
  return out.join(' ');
}

async function timed(fn: () => Promise<unknown>): Promise<number> {
  const t0 = process.hrtime.bigint();
  await fn();
  return Number(process.hrtime.bigint() - t0) / 1e6; // ms
}

async function main(): Promise<void> {
  const config = loadConfig();
  const models = discoverModels(config.modelsDir);
  const cap = resolvePiperConcurrency();

  const lines: string[] = [];
  const log = (s = '') => {
    lines.push(s);
    console.log(s);
  };

  log('# BENCHMARKS — Vozen baseline');
  log('');
  log('Generated by `npx tsx tools/bench.ts`. Real Piper process; isolated temporary cache.');
  log('Streaming is not enabled: time to first word equals total synthesis time below.');
  log('');
  log(`- Piper: \`${config.piperPath}\``);
  log(`- Modelos: ${models.length} em \`${config.modelsDir}\``);
  log(`- Cap de concorrência (PIPER_MAX_CONCURRENCY / max(1,núcleos-1)): **${cap}**`);
  log('');

  if (!existsSync(config.piperPath) && !config.piperPath.includes('/')) {
    // piperPath may be a command on the PATH; we test with --help.
    const probe = spawnSync(config.piperPath, ['--help'], { timeout: 5000 });
    if (probe.error) {
      log('> ⚠️ Piper was not found or executable; benchmark aborted.');
      writeFileSync(join(process.cwd(), 'BENCHMARKS.md'), lines.join('\n'));
      return;
    }
  }
  if (models.length === 0) {
    log('> ⚠️ No .onnx models found; benchmark aborted.');
    writeFileSync(join(process.cwd(), 'BENCHMARKS.md'), lines.join('\n'));
    return;
  }

  const pickModel = (...prefs: string[]): string =>
    prefs.find((p) => models.includes(p)) ?? models[0];
  const voicePt = pickModel('pt_PT-tugao-medium', 'pt_PT-tugão-medium', 'pt_BR-faber-medium');
  const voiceEn = pickModel('en_US-amy-medium', 'en_GB-alan-medium');
  log(`- Voz PT: \`${voicePt}\` · Voz EN: \`${voiceEn}\``);
  log('');

  const cacheDir = mkdtempSync(join(tmpdir(), 'vozen-bench-'));
  const engine = new PiperEngine(config.piperPath, config.modelsDir, new AudioCache(cacheDir, 0), {
    noiseScale: config.noiseScale,
    noiseW: config.noiseW,
    sentenceSilence: config.sentenceSilence,
  });

  try {
    const rssBefore = process.memoryUsage().rss;

    // ── COLD latency by size (guaranteed cache miss: unique text per run) ──
    const sizes: Array<{ name: string; n: number; runs: number }> = [
      { name: 'short (~6 words)', n: 6, runs: 8 },
      { name: 'medium (~30 words)', n: 30, runs: 8 },
      { name: 'long (~90 words)', n: 90, runs: 5 },
    ];

    log('## COLD synthesis latency (cache miss)');
    log('');
    log('| Size | Voice | runs | p50 (ms) | p95 (ms) | min | max |');
    log('|---|---|---:|---:|---:|---:|---:|');

    const warmSamples: Array<{ label: string; req: SynthRequest }> = [];

    for (const size of sizes) {
      for (const [vlabel, model] of [
        ['PT', voicePt],
        ['EN', voiceEn],
      ] as const) {
        const durs: number[] = [];
        let firstReq: SynthRequest | null = null;
        for (let i = 0; i < size.runs; i++) {
          const req: SynthRequest = { text: `${i} ${words(size.n)}`, model, speed: 1 };
          if (!firstReq) firstReq = req;
          durs.push(await timed(() => engine.synth(req)));
        }
        const s = stats(durs);
        log(
          `| ${size.name} | ${vlabel} | ${size.runs} | ${s.p50.toFixed(0)} | ${s.p95.toFixed(0)} | ${s.min.toFixed(0)} | ${s.max.toFixed(0)} |`,
        );
        if (firstReq) warmSamples.push({ label: `${size.name} ${vlabel}`, req: firstReq });
      }
    }
    log('');

    // ── WARM latency (cache hit): re-synthesizes the same requests already cached ──
    log('## WARM latency (cache hit)');
    log('');
    log('| Amostra | ms |');
    log('|---|---:|');
    for (const { label, req } of warmSamples) {
      const ms = await timed(() => engine.synth(req));
      log(`| ${label} | ${ms.toFixed(2)} |`);
    }
    log('');

    // ── Approximate spawn overhead: 1-word synthesis, cache miss × N ──
    log('## Spawn overhead (one-word synthesis)');
    log('');
    const spawnDurs: number[] = [];
    for (let i = 0; i < 10; i++) {
      spawnDurs.push(
        await timed(() => engine.synth({ text: `${i} ola`, model: voiceEn, speed: 1 })),
      );
    }
    const ss = stats(spawnDurs);
    log(
      `- p50 **${ss.p50.toFixed(0)} ms**, p95 ${ss.p95.toFixed(0)} ms (piso ≈ spawn + síntese mínima).`,
    );
    log('');

    // ── Cache hit-rate on a synthetic replay (chat: mix of repetitions) ──
    log('## Cache hit rate (synthetic replay)');
    log('');
    const phrases = ['bom dia', 'ola pessoal', 'tudo bem', 'ok', 'obrigado'];
    // 30 messages: 60% repetitions of the phrases above, 40% unique.
    let hits = 0;
    let total = 0;
    for (let i = 0; i < 30; i++) {
      const unique = i % 5 === 0;
      const text = unique ? `mensagem unica numero ${i}` : phrases[i % phrases.length];
      const req: SynthRequest = { text, model: voiceEn, speed: 1 };
      const key = (await import('../src/tts/cache')).cacheKey(req);
      const wasCached = new AudioCache(cacheDir, 0).get(key) !== null;
      if (wasCached) hits++;
      total++;
      await engine.synth(req);
    }
    log(
      `- ${hits}/${total} hits = **${((hits / total) * 100).toFixed(0)}%** neste replay (repetições típicas de chat).`,
    );
    log('> If production messages are usually unique, cache impact will be limited.');
    log('');

    const rssAfter = process.memoryUsage().rss;
    log('## Recursos');
    log('');
    log(
      `- RSS antes: ${(rssBefore / 1024 / 1024).toFixed(0)} MB · depois: ${(rssAfter / 1024 / 1024).toFixed(0)} MB`,
    );
    log('');
    log('---');
    log(
      '_Baseline before pool and streaming optimizations. Run again after changes for comparison._',
    );

    writeFileSync(join(process.cwd(), 'BENCHMARKS.md'), lines.join('\n') + '\n');
    console.log(`\n✅ BENCHMARKS.md written (${models.length} models, cap ${cap}).`);
  } finally {
    // Close the warm piper processes (if PIPER_PERSISTENT was ON) — otherwise the
    // event loop stays alive through the children and the process doesn't exit.
    shutdownPiperPool();
    rmSync(cacheDir, { recursive: true, force: true });
  }
}

main().catch((err) => {
  console.error('benchmark failed:', err);
  process.exit(1);
});
